theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "net"
device = "wlp59s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
speed_down = true
graph_up = false
interval = 1

[[block]]
block = "memory"
format_mem = "{Mup}%"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}GHz"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

#[[block]]
#block = "weather"
#format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
#service = { name = "openweathermap", api_key="ca6285ee7362d1ec68c5f515e78513ae", city_id = "2996944", units = "metric" }

[[block]]
block = "time"
format = "%F %T"
timezone = "Europe/Paris"
interval = 1
